######################
###      变化      ###
######################
#1. 程序可自定义默认Obj变量与Str变量,如{name}
#2. 程序可定义传入的额外变量

######################
## 组合额外变量格式 ##
######################
#提示: 多个额外变量之间会以空格进行连接
#{x}: 第x个额外变量,x>=1
#{x,}: 第x到最后个额外变量,x>=1
#{,y}: 第1到y个额外变量,y>=1
#{x,y}: 第x到y个额外变量,y>=x>=1
#{,}: 从开始到最后个额外变量

######################
###      格式      ###
######################
#变量
params:
  #获取对象列表(以Obj来标记)
  #(在程序中的返回结果是一个Object)
  getObjects:
    #以o开头代表从插件中获取对象
    #插件名:获取名([{str1},...])
    #获取名的方法中传入的变量都是Str
    o1: "LibCore:getLowerName({name})"
  #获取字符串列表(以Str来标记)
  #(在程序中的返回结果是一个String)
  getStrings:
    #以a开头代表从获取对象中获取值
    #获取对象名[:属性/方法([{str1},...])]
    #方法中传入的变量都是Str
    a1: "o1:toString()"

    #以b开头代表直接设置值,可包含变量
    #如果某个变量名不存在,则会原样保留
    b1: "xxx {str3}"

    #以c开头代表单个的组合额外变量
    c1: "{2,}"
